-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO response_types ("response_type") VALUES('token');
-- INSERT INTO response_types ("response_type") VALUES('code');
