-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- ALTER TABLE clients
-- ADD CONSTRAINT no_forbidden_characters
-- CHECK (check_forbidden_characters(name) IS FALSE);
