-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."authorization_codes" add column "client_user_id" uuid
--  not null;
