name: Hasura Deploy Test
on:
  push:
    branches: [master]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Migrate
        run: |
          echo "Install NPM Packages"
          npm i
          echo "Start migration"
          npx hasura migrate apply --endpoint ${{ secrets.HASURA_ENDPOINT }}  --admin-secret "${{ secrets.HASURA_SECRET }}" --project brew-oauth-server --all-databases
          npx hasura metadata apply --endpoint ${{ secrets.HASURA_ENDPOINT }} --admin-secret "${{ secrets.HASURA_SECRET }}" --project brew-oauth-server
          echo "Migration OK"
          npx hasura metadata diff --endpoint ${{ secrets.HASURA_ENDPOINT }} --admin-secret "${{ secrets.HASURA_SECRET }}" --project brew-oauth-server
          npx hasura migrate status --endpoint ${{ secrets.HASURA_ENDPOINT }} --admin-secret "${{ secrets.HASURA_SECRET }}" --project brew-oauth-server --all-databases
          echo "Migration status done"