name: Hasura Deploy Test
on:
  push:
    branches: [master]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Migrate
        run: |
          echo "Install NPM Packages"
          npm i
          echo "Start migration"
          npx hasura migrate apply --endpoint ${{ secrets.HASURA_ENDPOINT_TEST }}  --admin-secret "${{ secrets.HASURA_SECRET_TEST }}" --project oauth-server --database-name oauth
          npx hasura metadata apply --endpoint ${{ secrets.HASURA_ENDPOINT_TEST }} --admin-secret "${{ secrets.HASURA_SECRET_TEST }}" --project oauth-server
          echo "Migration OK"
          npx hasura metadata diff --endpoint ${{ secrets.HASURA_ENDPOINT_TEST }} --admin-secret "${{ secrets.HASURA_SECRET_TEST }}" --project oauth-server
          npx hasura migrate status --endpoint ${{ secrets.HASURA_ENDPOINT_TEST }} --admin-secret "${{ secrets.HASURA_SECRET_TEST }}" --project oauth-server --database-name oauth
          echo "Migration status done"
